### ISSUE TITLE
无重复模式的问题

### ISSUE THREAD

**Issue by tjucjw** [heimoshuiyu/lottery-assistant#1]
Hello  感谢作者的工作！

V1.5版本的程序，使用过程中发现即使选择了无重复模式，有时候也会出现重复的现象。比如三个人A B C，删除历史数据库，后开始抽取，可能会出现开始时连续两三次都是A.

realchouqian 函数中获取maxrange的值，maxrange = jsondata['range']是否应修改为maxrange = jsondata['range'] - 1 ?

或者 getrangedict 函数中 if index >= min and index <= max 改为 if index >= min and index < max？

**Comment by heimoshuiyu** [comment]
非常感谢你的建议
